# Generated by Django 4.1.7 on 2023-03-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='author',
        ),
    ]
